
(function($){Drupal.behaviors.breakingNews={attach:function(context,settings){var $prev_num=1;var $num=1;var $total=0;var $timeOut="";var $timeOutDelay=true;var $pause=false;function rotateTicker(){$total=$('.breaking-news li').length;$('.breaking-news li').hide();$('.breaking-news li').first().css('display','inline');}
function autoStart(){if($timeOutDelay){$timeOutDelay=false;}
else nextTicker();$timeOut=setTimeout(autoStart,3000);}
function nextTicker(){if($timeOut)clearTimeout($timeOut);$prev_num=$num;$num=$num+1;if($num>$total)$num=1;changeTicker();}
function prevTicker(){if($timeOut)clearTimeout($timeOut);$prev_num=$num;$num=$num-1;if($num<1)$num=$total;changeTicker();}
function pauseTicker(){if($timeOut)clearTimeout($timeOut);}
function changeTicker(){if($total>1){$(".breaking-news li:nth-child("+$prev_num+")").fadeOut('fast',function(){$(".breaking-news li:nth-child("+$num+")").fadeIn('slow');});}}
$(document).ready(function(){if($('.breaking-news').length&&!$.cookie($('.breaking-news').attr('id'))){$('body').addClass('breakingNewsLoaded');$('.breaking-news').slideDown(function(){$.event.trigger({type:'breaking_news_open'});});}
$('.breaking-news li').hover(function(){pauseTicker();});$('.breaking-news li').mouseleave(function(){$timeOutDelay=true;if(!$pause)autoStart();});$('.breaking-news .close').on('click',function(){$('body').removeClass('breakingNewsLoaded');$.cookie($('.breaking-news').attr('id'),true);$('.breaking-news').slideUp(function(){$.event.trigger({type:'breaking_news_close'});});});rotateTicker();autoStart();});}}})(jQuery);(function(){'use strict';var f,g=[];function l(a){g.push(a);1==g.length&&f()}function m(){for(;g.length;)g[0](),g.shift()}f=function(){setTimeout(m)};function n(a){this.a=p;this.b=void 0;this.f=[];var b=this;try{a(function(a){q(b,a)},function(a){r(b,a)})}catch(c){r(b,c)}}var p=2;function t(a){return new n(function(b,c){c(a)})}function u(a){return new n(function(b){b(a)})}function q(a,b){if(a.a==p){if(b==a)throw new TypeError;var c=!1;try{var d=b&&b.then;if(null!=b&&"object"==typeof b&&"function"==typeof d){d.call(b,function(b){c||q(a,b);c=!0},function(b){c||r(a,b);c=!0});return}}catch(e){c||r(a,e);return}a.a=0;a.b=b;v(a)}}
function r(a,b){if(a.a==p){if(b==a)throw new TypeError;a.a=1;a.b=b;v(a)}}function v(a){l(function(){if(a.a!=p)for(;a.f.length;){var b=a.f.shift(),c=b[0],d=b[1],e=b[2],b=b[3];try{0==a.a?"function"==typeof c?e(c.call(void 0,a.b)):e(a.b):1==a.a&&("function"==typeof d?e(d.call(void 0,a.b)):b(a.b))}catch(h){b(h)}}})}n.prototype.g=function(a){return this.c(void 0,a)};n.prototype.c=function(a,b){var c=this;return new n(function(d,e){c.f.push([a,b,d,e]);v(c)})};
function w(a){return new n(function(b,c){function d(c){return function(d){h[c]=d;e+=1;e==a.length&&b(h)}}var e=0,h=[];0==a.length&&b(h);for(var k=0;k<a.length;k+=1)u(a[k]).c(d(k),c)})}function x(a){return new n(function(b,c){for(var d=0;d<a.length;d+=1)u(a[d]).c(b,c)})};window.Promise||(window.Promise=n,window.Promise.resolve=u,window.Promise.reject=t,window.Promise.race=x,window.Promise.all=w,window.Promise.prototype.then=n.prototype.c,window.Promise.prototype["catch"]=n.prototype.g);}());

(function(){'use strict';var h=!!document.addEventListener;function k(a,b){h?a.addEventListener("scroll",b,!1):a.attachEvent("scroll",b)}function w(a){document.body?a():h?document.addEventListener("DOMContentLoaded",a):document.onreadystatechange=function(){"interactive"==document.readyState&&a()}};function x(a){this.a=document.createElement("div");this.a.setAttribute("aria-hidden","true");this.a.appendChild(document.createTextNode(a));this.b=document.createElement("span");this.c=document.createElement("span");this.h=document.createElement("span");this.f=document.createElement("span");this.g=-1;this.b.style.cssText="display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.c.style.cssText="display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";
this.f.style.cssText="display:inline-block;position:absolute;height:100%;width:100%;overflow:scroll;font-size:16px;";this.h.style.cssText="display:inline-block;width:200%;height:200%;font-size:16px;";this.b.appendChild(this.h);this.c.appendChild(this.f);this.a.appendChild(this.b);this.a.appendChild(this.c)}
function y(a,b){a.a.style.cssText="min-width:20px;min-height:20px;display:inline-block;overflow:hidden;position:absolute;width:auto;margin:0;padding:0;top:-999px;left:-999px;white-space:nowrap;font:"+b+";"}function z(a){var b=a.a.offsetWidth,c=b+100;a.f.style.width=c+"px";a.c.scrollLeft=c;a.b.scrollLeft=a.b.scrollWidth+100;return a.g!==b?(a.g=b,!0):!1}function A(a,b){function c(){var a=l;z(a)&&null!==a.a.parentNode&&b(a.g)}var l=a;k(a.b,c);k(a.c,c);z(a)};function B(a,b){var c=b||{};this.family=a;this.style=c.style||"normal";this.weight=c.weight||"normal";this.stretch=c.stretch||"normal"}var C=null,D=null,H=!!window.FontFace;function I(){if(null===D){var a=document.createElement("div");try{a.style.font="condensed 100px sans-serif"}catch(b){}D=""!==a.style.font}return D}function J(a,b){return[a.style,a.weight,I()?a.stretch:"","100px",b].join(" ")}
B.prototype.a=function(a,b){var c=this,l=a||"BESbswy",E=b||3E3,F=(new Date).getTime();return new Promise(function(a,b){if(H){var q=function(){(new Date).getTime()-F>=E?b(c):document.fonts.load(J(c,c.family),l).then(function(b){1<=b.length?a(c):setTimeout(q,25)},function(){b(c)})};q()}else w(function(){function r(){var b;if(b=-1!=e&&-1!=f||-1!=e&&-1!=g||-1!=f&&-1!=g)(b=e!=f&&e!=g&&f!=g)||(null===C&&(b=/AppleWebKit\/([0-9]+)(?:\.([0-9]+))/.exec(window.navigator.userAgent),C=!!b&&(536>parseInt(b[1],
10)||536===parseInt(b[1],10)&&11>=parseInt(b[2],10))),b=C&&(e==t&&f==t&&g==t||e==u&&f==u&&g==u||e==v&&f==v&&g==v)),b=!b;b&&(null!==d.parentNode&&d.parentNode.removeChild(d),clearTimeout(G),a(c))}function q(){if((new Date).getTime()-F>=E)null!==d.parentNode&&d.parentNode.removeChild(d),b(c);else{var a=document.hidden;if(!0===a||void 0===a)e=m.a.offsetWidth,f=n.a.offsetWidth,g=p.a.offsetWidth,r();G=setTimeout(q,50)}}var m=new x(l),n=new x(l),p=new x(l),e=-1,f=-1,g=-1,t=-1,u=-1,v=-1,d=document.createElement("div"),
G=0;d.dir="ltr";y(m,J(c,"sans-serif"));y(n,J(c,"serif"));y(p,J(c,"monospace"));d.appendChild(m.a);d.appendChild(n.a);d.appendChild(p.a);document.body.appendChild(d);t=m.a.offsetWidth;u=n.a.offsetWidth;v=p.a.offsetWidth;q();A(m,function(a){e=a;r()});y(m,J(c,'"'+c.family+'",sans-serif'));A(n,function(a){f=a;r()});y(n,J(c,'"'+c.family+'",serif'));A(p,function(a){g=a;r()});y(p,J(c,'"'+c.family+'",monospace'))})})};window.FontFaceObserver=B;window.FontFaceObserver.prototype.check=B.prototype.a;"undefined"!==typeof module&&(module.exports=window.FontFaceObserver);}());
;/**/

function socialnewsletterValidateEmail(email){var re=/^(([^<>()[\]\\.,;:\s@\"]+(\.[^<>()[\]\\.,;:\s@\"]+)*)|(\".+\"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;return re.test(email);}
(function($){$(document).ready(function(){if($('.social-follow').length>0){$(".social-follow .icons li.mail").addClass('active');$(".social-follow .buttons li.mail").show().addClass('active');$(".social-follow .icons li").hover(function(){var buttonIndex=$(this).index();$(".social-follow .buttons li.active").hide().removeClass('active');$(".social-follow .buttons li").eq(buttonIndex).show().addClass('active');$(this).addClass('active');$(".social-follow .icons li").not(this).removeClass('active');});}
if($('#newsletter_social_form, .newsletter_pulse_form, .newsletter_social_form').length>0){$('#newsletter_social_form, .newsletter_pulse_form, .newsletter_social_form').each(function(){var newsletterForm=$(this);newsletterForm.submit(function(e){var newsletterFormURL='/newsletter-social';var ty='<div class="np-ty-text"><b>Thank you for subscribing.</b><br />Please check your inbox for your welcome email.</div>';var processing='<div class="processing">Processing...</div>';if($(".ty-message")[0]){ty=$(".ty-message").html();}
if($(".process-message")[0]){processing=$(".process-message").html();}
var emailInput=$(this).find('input[type=text]');if(emailInput.length>0&&!socialnewsletterValidateEmail(emailInput.val())){newsletterForm.find('.np-error').fadeIn();emailInput.addClass('error');return false;}else{newsletterForm.find('.np-error').fadeOut();}
var formData=$(this).serialize();newsletterForm.find('.np-email').html(processing);$.ajax({'type':'GET','dataType':'jsonp','jsonpCallback':'newsletter_social','url':newsletterFormURL,'data':formData,'success':function(data){newsletterForm.find('.np-email').html(ty);}});e.preventDefault();});});}});})(jQuery);(function($){$(document).ready(function(){if($('.most-popular').length>0&&typeof $('.most-popular').tabs!="undefined"){$('.most-popular').tabs();}
$('.item-shares-wrapper').mouseenter(function(){$(this).find('.item-shares').addClass('hidden');$(this).find('.addthis_toolbox').removeClass('hidden');});$('.item-shares-wrapper').mouseleave(function(){$(this).find('.item-shares').removeClass('hidden');$(this).find('.addthis_toolbox').addClass('hidden');});});})(jQuery);
(function($){Drupal.behaviors.dataLayer={langPrefixes:function langPrefixes(){var languages=Drupal.settings.dataLayer.languages,langList=[];for(var lang in languages){if(languages[lang].prefix!==''){langList.push(languages[lang].prefix);}}
return langList;},attach:function(){return}};})(jQuery);;