(function(q){function w(){}function m(b,r,a,c){this.L=new Date;this.R=b;this.G=a||[];this.K=c||null;this.level=r;this.G=JSON.parse(JSON.stringify(this.G))}function n(){this.o=[]}function c(b){this.b=b;this.j=b.getSlotElementId();this.A=b.getAdUnitPath();this.Y=b.getSlotId().getId();this.H="/"!=this.A.charAt(0)?"/"+this.A.toString():this.A.toString();this.C=[this.H,this.j].join("|");this.v=b.getOutOfPage();this.l=null;this.m=!1;this.M=[];this.w=[];this.i=!1;this.s={fetched:0,rendered:0,bidRequests:0,
bids:0,refresh:0,display:0};this.c=this.u=!1;this.X()}function x(){var b="SB"+(new Date).getTime().toString()+Math.floor(1E5*Math.random());return"function"===typeof window[b]?x():b}function e(){this.c=[];this.j={};this.l={};this.i=[];this.w=this.h=null;this.b=new n;this.m={};this.A=[];this.da=[]}var v={log:1,warn:3,error:5};m.prototype.getType=function(){return this.R};m.prototype.getSlot=function(){return this.K};m.prototype.getMessageArgs=function(){return this.G};m.prototype.getTimestamp=function(){return this.L};
m.prototype.toObject=function(){return{ts:this.L,typeId:this.R,messageArgs:this.G,slot:this.K?this.K.toObject():null,level:this.level}};m.prototype.getLevel=function(){return this.level};n.prototype.log=function(b,r,a){b=new m(b,v.log,r,a);this.o.push(b)};n.prototype.warn=function(b,r,a){b=new m(b,v.warn,r,a);this.o.push(b)};n.prototype.error=function(b,a,d){b=new m(b,v.error,a,d);this.o.push(b)};n.prototype.getLogs=function(){return this.o};n.prototype.getLogBySlot=function(b){var a=[];b="object"===
typeof b?b.getElementID():b+"";for(var d=0;d<this.o.length;d++){var c=this.o[d],f=c.getSlot();f&&f.getElementID()===b&&a.push(c)}return a};n.prototype.getLogsSimple=function(){return this.o.map(function(b){return b.toObject()})};n.prototype.getSlotLogsSimple=function(b){return this.getLogBySlot(b).map(function(b){return b.toObject()})};c.log=function(b,a,d){w(b,a,d)};c.b=function(){};c.setLogger=function(b){w=b};c.c=[];c.acceptedSizes=function(b){return 1===arguments.length?(c.c=b,c):c.c};c.setDisplay=
function(b){c.b=b};c.prototype.X=function(){var b=this,a=this.b;a.getMorpheusSlot=function(){return b};var d=a.fetchStarted;a.fetchStarted=function(f){d.apply(a,arguments);c.log(10,["fetchStarted"],b)};var g=a.fetchEnded;a.fetchEnded=function(){b.s.fetched++;c.log(10,["fetchEnded"],b);g.apply(a,arguments);b.c=!1}};c.prototype.V=function(){return this.b.getTargetingMap()};c.prototype.F=function(b){var a={};"object"===typeof b?a=b:a[b]=void 0;for(var d in a)this.b.setTargeting(d,a[d])};c.prototype.S=
function(b){var a=this.V(),d={},g=!1;if("function"===typeof b)for(var f in a)b(f,a[f])?g=!0:d[f]=a[f];else g=!0;g&&(c.log(24,[this.getKeymakerKey()],this),this.b.clearTargeting(),this.F(d))};c.prototype.I=function(){this.S(function(b){return"sbi_"===b.substr(0,4)});this.c=!1;c.log(14,[this.getKeymakerKey()],this)};c.prototype.display=function(){0===this.s.display++?(c.log(15,[this.getKeymakerKey()],this),c.b(this.j)):c.log(25,[this.getKeymakerKey()],this)};c.prototype.T=function(b){b=b||!1;if(this.v)return[];
for(var a="",d=[],g=this.b.getSizes(window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth,window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight),f=0;f<g.length;f++)a=g[f],a=[a.getWidth(),a.getHeight()],(b||-1!=c.acceptedSizes().indexOf(a.join("x")))&&d.push(a);return d};c.prototype.U=function(){return this.B().join(",")};c.prototype.B=function(b){var a=[];this.v||this.m?a=[]:this.l&&0<this.l.length?a=this.l.map(function(b){return b.join("x")}):
a=this.T(b);return a.map(function(b){return b.join("x")})};c.prototype.W=function(){return this.m||this.c||this.i?!1:0<this.B().length};c.prototype.isUnfetched=function(){return!this.u&&!this.i};c.prototype.getElementID=function(){return this.j};c.prototype.getKeymakerKey=function(){return this.C};c.prototype.setBid=function(b){this.w.push({L:new Date,ea:b});this.F(b);b.hasOwnProperty("sbi_aid")?(this.M.push(b.sbi_aid),this.s.bids++,c.log(13,[this.getKeymakerKey(),b],this),b.hasOwnProperty("sbi_dozer")&&
c.log(27,[this.getKeymakerKey(),b],this)):c.log(26,[this.getKeymakerKey()],this);this.c=!0;this.i=!1;return this};c.prototype.addToRequestIfNeeded=function(b){this.u=!0;this.W()&&(this.I(),this.i=!0,this.s.bidRequests++,b[this.C]=this.U());return this.j};c.prototype.getSlot=function(){return this.b};c.prototype.getCounts=function(){return this.s};c.prototype.getHistory=function(){return this.w};c.prototype.toObject=function(){return{initialChecked:this.u,counts:this.s,history:this.w,elementID:this.j,
keyMakerKey:this.C,adUnitPath:this.H,isOutOfPage:this.v,sizesOverride:this.l,disabledOverride:this.m,sizes:this.B(!0),slotId:this.Y}};c.prototype.getOutOfPage=function(){return this.v};c.prototype.getBidSet=function(){return this.c};c.prototype.getBidding=function(){return this.i};c.prototype.setSizes=function(b){this.l=b;c.log(40,[this.getKeymakerKey(),b],this);return this};c.prototype.disable=function(){this.m=!0;c.log(42,[this.getKeymakerKey()],this);return this};c.prototype.getInitialChecked=
function(){return this.u};e.prototype.addSlot=function(b){b=new c(b);var a=b.getElementID();this.j[a]=this.l[b.getKeymakerKey()]=b;this.c.push(b);b.getOutOfPage()?this.b.log(36,[b.getKeymakerKey()],b):this.b.log(11,[b.getKeymakerKey()],b);this.m.hasOwnProperty(a)&&b.setSizes(this.m[a]);-1!==this.A.indexOf(a)&&b.disable();return b};e.prototype.F=function(b,a){var d=this.v(b);d?d.setBid(a):this.b.log(21,[b])};e.prototype.getBidsForUnfetched=function(b){var a=this;"function"===!typeof b&&(b=function(){});
this.b.log(22,[]);for(var d=[],g=0;g<a.c.length;g++)a.c[g].isUnfetched()&&d.push(a.c[g]);a.B(d,function(){var d=a.i;a.i=[];for(var g=0;g<d.length;g++){var h=d[g];if("object"===typeof h){var e=h.getCounts();h.getInitialChecked()&&!h.getBidding()?1>e.display&&h.display():a.i.push(h)}else c.b(h)}b()})};e.prototype.B=function(b,a){var d={};b.map(function(b){return b.addToRequestIfNeeded(d)});this.b.log(23,[d]);this.I(d,a)};e.prototype.H=function(b){this.h.setTargeting("sbi_dc",b)};e.prototype.initialize=
function(b,a){this.w=b;this.h=b.pubads();e.setLogger(this.b);c.setDisplay(this.w.display);c.acceptedSizes(a)};e.prototype.M=function(b){this.H(b)};e.prototype.I=function(b,a){var d=this;if("object"===typeof b&&0<Object.keys(b).length){var c=x(),f=!1;window[c]=function(c){if(!f){d.M(c.sbi_dc);for(var g in c.slots)d.F(g,c.slots[g]);a(b)}};var e="//apex.go.sonobi.com/trinity.js?key_maker="+JSON.stringify(b)+"&s="+Math.floor(1E5*Math.random())+"&cv="+c;d.C(e,function(e){if(e){f=!0;window[c]=function(){};
for(var k in b)d.F(k,!1);a(b);a=function(){}}})}else a(b)};e.prototype.queueDisplay=function(b){var a=this.u(b);a||(a=b);return this.i.push(a)};e.prototype.getSlotByElementId=function(b){return this.u(b)};e.prototype.u=function(b){return this.j.hasOwnProperty(b)?this.j[b]:!1};e.prototype.v=function(b){return this.l.hasOwnProperty(b)?this.l[b]:!1};e.prototype.getSlotByKeymaker=function(b){return this.v(b)};e.prototype.setDisplayFunction=function(b){c.setDisplay(b)};e.prototype.C=function(b,a){if(null!=
b){null==a&&(a=function(){});try{var d=document.createElement("script");d.type="text/javascript";d.async=!0;d.src=b;if(a!=function(){}){var c=setTimeout(function(){try{a(!0)}catch(b){}a=function(){}},1500);d.readyState?d.onreadystatechange=function(){clearTimeout(c);if("loaded"==d.readyState||"complete"==d.readyState){d.onreadystatechange=null;try{a()}catch(b){}a=function(){}}}:d.onload=function(){clearTimeout(c);try{a()}catch(b){}a=function(){}}}var f=document.getElementsByTagName("script")[0];f.parentNode.insertBefore(d,
f)}catch(e){}}};e.prototype.getSlots=function(){return this.c};e.prototype.getLogger=function(){return this.b};e.prototype.getAllLogs=function(){return this.b.getLogs()};e.prototype.getLogBySlot=function(b){return this.b.getLogBySlot(b)};e.log=function(){};e.setLogger=function(b){c.setLogger(b.log.bind(b))};e.prototype.loadDebugger=function(b){this.C("//mtrx.go.sonobi.com/morpheusLog.debug.js",function(){window.console&&"function"===typeof window.console.log&&console.log("LOADED DEBUG SCRIPT!");"function"===
typeof b&&b()})};e.prototype.setSizes=function(b,a){var d=this.getSlotByElementId(b);d?d.setSizes(a):(this.m[b]=a,this.b.log(41,[b,a]))};e.prototype.setDisabledSlot=function(a){var c=this.getSlotByElementId(a);c?c.disable():(this.A.push(a),this.b.log(43,[a]))};var a={ca:1500,J:"300x250 300x600 300x1050 300x50 320x50 320x100 728x90 160x600 120x600 970x250 970x90 300x100 970x66".split(" "),Z:!1,D:[]};if(window[q]&&"object"===typeof window[q])for(var t in window[q])switch(t){case "cmd":a.D=window[q][t];
break;case "acceptedSizes":a.J=window[q][t];break;case "timeout":a.ca=window[q][t]}a.version="2.2.1";a.ba=!1;a.N=!1;a.g=null;a.da=[];a.getManager=function(){return a.g};a.O=function(){var b=a.g,c=a.a.f.enableServices;a.P=!1;a.a.f.enableServices=function(){a.log(10,["enableServices"]);a.P||(a.P=!0);return c.apply(this,arguments)};var d=a.a.h.enableSingleRequest;a.a.h.enableSingleRequest=function(){a.log(10,["enableSingleRequest"]);var b=d.apply(this,arguments);return a.ba=b};var e=a.a.h.disableInitialLoad;
a.a.h.disableInitialLoad=function(){a.log(10,["disableInitialLoad"]);a.N=!0;return e.apply(this,arguments)};var f=a.a.f.defineOutOfPageSlot;a.a.f.defineOutOfPageSlot=function(){var a=f.apply(this,arguments);b.addSlot(a);return a};var k=a.a.f.defineSlot;a.a.f.defineSlot=function(){var a=k.apply(this,arguments);b.addSlot(a);return a};var h=a.a.f.display;a.a.f.display=function(){var c=arguments,d=arguments[0],e=a.g.getSlotByElementId(d);a.log(31,[d],e);if(a.N)return a.log(33,[d],e),h.apply(this,c);if(d&&
e&&e.getBidSet())return a.log(34,[d],e),e.display();d&&e&&(e.getBidding()||e.getInitialChecked())?b.queueDisplay(d):(b.queueDisplay(d),b.getBidsForUnfetched.bind(b)(function(){a.log(35,[])}))};var m=a.a.h.refresh;a.a.h.refresh=function(){var d=[],c=arguments,e=0;if(0<arguments.length&&"[object Array]"===Object.prototype.toString.call(arguments[0])){e=arguments[0].length;a.log(28,[e]);for(var f=0;f<arguments[0].length;f++){var g=arguments[0][f];g&&"function"===typeof g.getMorpheusSlot?d.push(g.getMorpheusSlot()):
a.log(30,[g,f])}}else a.log(28,[0]),d=a.g.getSlots();b.B(d,function(){for(var b=0;b<d.length;b++)d[b].s.refresh++;a.log(29,[e]);m.apply(a.a.h,c)})}};a.$=function(){a.g=new e;var b=a.g.getLogger();a.log=b.log.bind(b);a.log(16,[]);a.a={};window.googletag=window.googletag||{};a.a.f=window.googletag;a.a.f.cmd=a.a.f.cmd||[];null!=googletag.cmd.length?(a.log(17,[]),a.log(18,[]),a.log(19,[]),a.a.f.cmd.unshift(function(){a.a.h=googletag.pubads();a.g.initialize(window.googletag,a.J);a.O()})):("-1"!=function(){return a.a.f.getEventLog().getAllEvents().map(function(a){return a.getMessage().getMessageId()})}().indexOf(8)&&
a.log(20,[]),a.a.f.cmd.push(function(){a.a.h=googletag.pubads();a.g.initialize(window.googletag,a.J);a.O();for(var b=a.a.h.getSlots(),d=0;d<b.length;d++)a.g.addSlot(b[d])}));a.aa();return a};a.aa=function(){var b=0,c=a.D.length;if(0<a.D.length)for(a.log(37,[c]);0<a.D.length;){var d=a.D.shift();a.log(38,[b++,c]);d()}};a.outputCypherLog=function(){a.Z=!0;window.hasOwnProperty("SbiDebug")?window.SbiDebug.outputLog():a.g.loadDebugger(function(){setTimeout(function(){window.SbiDebug.outputLog()},100)})};
a.log=function(){};a.setSlotSizes=function(b,c){a.g.setSizes(b,c)};a.disableSlot=function(b){a.g.setDisabledSlot(b)};a.enableReactiveSizes=function(){a.log(39,["sbi_morpheus.enableReactiveSizes"])};a.callOperator=function(){a.log(39,["sbi_morpheus.callOperator"])};a.register=function(){a.log(39,["sbi_morpheus.register"])};window[q]=a.$();(function(){"object"!=typeof JSON&&(JSON={});(function(){function b(a){return 10>a?"0"+a:a}function c(a){return f.lastIndex=0,f.test(a)?'"'+a.replace(f,function(a){var b=
m[a];return"string"==typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function d(a,b){var e,f,g,m,p,u=k,l=b[a];switch(l&&"object"==typeof l&&"function"==typeof l.toJSON&&(l=l.toJSON(a)),"function"==typeof n&&(l=n.call(b,a,l)),typeof l){case "string":return c(l);case "number":return isFinite(l)?l+"":"null";case "boolean":case "null":return l+"";case "object":if(!l)return"null";if(k+=h,p=[],"[object Array]"===Object.prototype.toString.apply(l)){m=l.length;for(e=0;m>e;e+=
1)p[e]=d(e,l)||"null";return g=0===p.length?"[]":k?"[\n"+k+p.join(",\n"+k)+"\n"+u+"]":"["+p.join(",")+"]",k=u,g}if(n&&"object"==typeof n)for(m=n.length,e=0;m>e;e+=1)"string"==typeof n[e]&&(f=n[e],g=d(f,l),g&&p.push(c(f)+(k?": ":":")+g));else for(f in l)Object.prototype.hasOwnProperty.call(l,f)&&(g=d(f,l),g&&p.push(c(f)+(k?": ":":")+g));return g=0===p.length?"{}":k?"{\n"+k+p.join(",\n"+k)+"\n"+u+"}":"{"+p.join(",")+"}",k=u,g}}"function"!=typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(a.valueOf())?
a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return a.valueOf()});var e,f,k,h,m,n;"function"!=typeof JSON.stringify&&(f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,m={"\b":"\\b","    ":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',
"\\":"\\\\"},JSON.stringify=function(a,b,c){var e;if(k="",h="","number"==typeof c)for(e=0;c>e;e+=1)h+=" ";else"string"==typeof c&&(h=c);if(n=b,b&&"function"!=typeof b&&("object"!=typeof b||"number"!=typeof b.length))throw Error("JSON.stringify");return d("",{"":a})});"function"!=typeof JSON.parse&&(e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,JSON.parse=function(a,b){function c(a,d){var e,f,g=a[d];if(g&&"object"==typeof g)for(e in g)Object.prototype.hasOwnProperty.call(g,
e)&&(f=c(g,e),void 0!==f?g[e]=f:delete g[e]);return b.call(a,d,g)}var d;if(a+="",e.lastIndex=0,e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})),/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),"function"==typeof b?c({"":d},""):d;throw new SyntaxError("JSON.parse");})})();Object.keys||
(Object.keys=function(){var a=Object.prototype.hasOwnProperty,c=!{toString:null}.propertyIsEnumerable("toString"),d="toString toLocaleString valueOf hasOwnProperty isPrototypeOf propertyIsEnumerable constructor".split(" "),e=d.length;return function(f){if("object"!==typeof f&&("function"!==typeof f||null===f))throw new TypeError("Object.keys called on non-object");var k=[],h;for(h in f)a.call(f,h)&&k.push(h);if(c)for(h=0;h<e;h++)a.call(f,d[h])&&k.push(d[h]);return k}}());Function.prototype.bind||
(Function.prototype.bind=function(a){function c(){return f.apply(this instanceof d?this:a,e.concat(Array.prototype.slice.call(arguments)))}function d(){}if("function"!=typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var e=Array.prototype.slice.call(arguments,1),f=this;return d.prototype=this.prototype,c.prototype=new d,c})})()})("sbi_morpheus");
//2.2.1